---
title: Maggie's Rentals
timezone: UTC
collections:
  apartments:
    title: Apartments
    output: true
  buildings:
    title: Buildings
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: apartments
  values:
    slideshow:
    - image: 
      description: 
    building: 
    is available: true
    bedrooms: 
    bathrooms: 
    available at: 
    layout: apartment
- scope:
    path: ''
    type: buildings
  values:
    image: 
    Google Map Text: 
    Apartments:
    - 
    layout: building
email: maggiegd@verizon.net
telephone: "(401) 739-5424"
address: "P.O. Box 6134 \n Warwick, RI 02886"
description: "Apartments for rent in Providence, Rhode Island \n"
baseurl: 
url: https://alexandreaco.github.io/maggiesrentals.github.io
markdown: kramdown
