---
title: Maggie's Rentals
timezone: UTC
collections:
  apartments:
    title: Apartments
    output: true
  buildings:
    title: Buildings
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: alexandref@gmail.com
description: "Apartments for rent in Providence, Rhode Island \n"
baseurl:
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
defaults:
  -
    scope:
      type: apartments
    values:
      images:
      building:
      is available: true
