---
title: Maggie's Rentals
timezone: UTC
collections:
  apartments:
    title: Apartments
    output: true
  buildings:
    title: Buildings
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: apartments
  values:
    slideshow:
    - image: 
      description: 
    building: 
    is available: true
    template: apartment
- scope:
    path: ''
    type: buildings
  values:
    image: 
    Google Map Text: 
    Apartments: 
    layout: building
email: alexandref@gmail.com
description: "Apartments for rent in Providence, Rhode Island \n"
baseurl: 
url: https://alexandreaco.github.io/maggiesrentals.github.io
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
